-- Boston House Price table
-- CRIM, ZN, INDUS, CHAS, NX, RM, AGE, DIS, RAD, TAX, PTRATIO, B, LSTAT, MEDV

CREATE TABLE BOOSTON_HOUSE_PRICE (
    CRIM    NUMBER(10,5) NOT NULL,
    ZN      NUMBER(5,1)  NOT NULL,
    INDUS   NUMBER(5,2)  NOT NULL,
    CHAS    NUMBER(1,0)  NOT NULL,
    NX      NUMBER(5,4)  NOT NULL,
    RM      NUMBER(5,3)  NOT NULL,
    AGE     NUMBER(5,1)  NOT NULL,
    DIS     NUMBER(7,4)  NOT NULL,
    RAD     NUMBER(3,0)  NOT NULL,
    TAX     NUMBER(6,1)  NOT NULL,
    PTRATIO NUMBER(4,1)  NOT NULL,
    B       NUMBER(6,2)  NOT NULL,
    LSTAT   NUMBER(5,2)  NOT NULL,
    MEDV    NUMBER(5,1)  NOT NULL
);

-- 필요 시 데이터 초기화
-- DELETE FROM BOOSTON_HOUSE_PRICE;
-- COMMIT;
