select * from book;
select bookname, price from book;
select publisher from book;
select DISTINCT publisher from book;
select * FROM book WHERE  price < 20000;
SELECT * FROM book WHERE (price >=10000) AND (price<=20000);
SELECT * FROM book WHERE price BETWEEN 10000 AND 20000;
SELECT * FROM book WHERE(publisher like'굿스포츠') OR (publisher like '대한미디어');
SELECT * FROM book WHERE publisher IN('굿스포츠','대한미디어');
SELECT * FROM book WHERE Bookname LIKE '축구의 역사'; 
SELECT * FROM book WHERE Bookname LIKE '%축구%';
SELECT * FROM book WHERE Bookname LIKE '_구%';
SELECT * FROM book WHERE (Bookname LIKE '%축구%') AND (price >= 20000);
SELECT * FROM book WHERE publisher ='굿스포츠' OR publisher = '대한미디어';
SELECT BOOKNAME FROM book ORDER BY BOOKNAME;
SELECT * FROM BOOK ORDER BY price, bookname;
SELECT * FROM BOOK ORDER BY price DESC, publisher ASC;
SELECT * FROM ORDERS;
SELECT SUM(price) FROM BOOK;
SELECT SUM(saleprice) FROM ORDERS;
SELECT SUM(saleprice) AS Total, AVG(saleprice) AS Average, MIN(saleprice) AS Minimum, MAX(saleprice) AS Maximum FROM ORDERS;
SELECT SUM(saleprice) AS 총매출 FROM ORDERS WHERE custid = 2;
SELECT SUM(saleprice)AS 총판매액 ,COUNT(*) AS 도서수량, custid FROM ORDERS  group by custid ;
SELECT Count(*) FROM orders group by custid;
SELECT * FROM ORDERS;
SELECT custid, COUNT(*) FROM ORDERS  GROUP BY CUSTID ;
SELECT COUNT(custid) from orders where saleprice >= 8000 group by custid having count(custid) >=2;
SELECT BOOKNAME FROM BOOK WHERE BOOKID = 1;
SELECT BOOKNAME FROM BOOK WHERE PRICE >= 20000;
SELECT SUM(SALEPRICE) FROM ORDERS WHERE CUSTID = 1;
SELECT COUNT(*) FROM ORDERS WHERE CUSTID = 1;
SELECT COUNT(DISTINCT BOOKID) FROM BOOK;
SELECT COUNT(DISTINCT publisher) FROM book;
select * from customer, orders where customer.custid = orders.custid;
select * from customer, orders;
SELECT * FROM CUSTOMER, ORDERS WHERE CUSTOMER.CUSTID = ORDERS.CUSTID ORDER BY ORDERS.CUSTID;
SELECT customer.name, book.bookname FROM CUSTOMER, BOOK;
SELECT customer.name, book.bookname FROM CUSTOMER, BOOK, ORDERS WHERE CUSTOMER.CUSTID = ORDERS.CUSTID AND ORDERS.BOOKID = BOOK.BOOKID;
SELECT customer.name, book.bookname FROM CUSTOMER, BOOK, ORDERS WHERE book.price = 20000 AND CUSTOMER.CUSTID = ORDERS.CUSTID AND ORDERS.BOOKID = BOOK.BOOKID;