SELECT Customer.name, saleprice FROM Customer LEFT OUTER JOIN Orders ON CUSTOMER.CUSTID = ORDERS.CUSTID;

SELECT * FROM ORDERS;

SELECT * FROM CUSTOMER;

SELECT * FROM BOOK ;

SELECT BOOKNAME FROM BOOK WHERE price = (SELECT MAX(price) FROM BOOK) ;

SELECT name FROM CUSTOMER where custid IN (SELECT custid FROM ORDERS);
SELECT NAME FROM CUSTOMER MINUS SELECT NAME FROM CUSTOMER WHERE CUSTID IN (SELECT CUSTID FROM ORDERS);
SELECT NAME, ADDRESS FROM CUSTOMER WHERE CUSTID IN (SELECT CUSTID FROM ORDERS WHERE CUSTOMER.CUSTID = ORDERS.CUSTID);

SELECT COUNT(DISTINCT PUBLISHER) FROM BOOK  WHERE bookid IN (SELECT bookid from orders where custid in (select custid from customer where NAME = '박지성'));
CREATE TABLE NEWbook(
bookid number,
bookname varchar2(20),
publisher varchar2(20),
price number,
primary key (bookname, publisher));
CREATE TABLE NEWCUSTOMER(
CUSTID NUMBER PRIMARY KEY,
name VARCHAR2(40),
address VARCHAR2(40),
phone VARCHAR2(30));

CREATE TABLE NEWORDERS(
ORDERID NUMBER PRIMARY KEY,
CUSTID NUMBER NOT NULL,
BOOKID NUMBER NOT NULL,
SALEPRICE NUMBER,
ORDERDATE DATE,
FOREIGN KEY(CUSTID) REFERENCES NEWCUSTOMER(CUSTID) ON DELETE CASCADE );

ALTER TABLE NEWBOOK ADD ISBN VARCHAR2(13);
ALTER TABLE NEWBOOK MODIFY ISBN NUMBER;
ALTER TABLE NEWBOOK DROP COLUMN ISBN ;
ALTER TABLE NEWBOOK MODIFY BOOKID NUMBER NOT NULL;
ALTER TABLE NEWBOOK ADD PRIMARY KEY(BOOKID);
INSERT INTO BOOK(BOOKID, BOOKNAME, PUBLISHER, PRICE) VALUES(11,'스포츠의학','한솔의학서적',90000);
COMMIT;

UPDATE CUSTOMER SET ADDRESS = '대한민국 부산' WHERE CUSTID = 5;

 -- 보스톤 집값 테이블 만들기
 -- CRIM,ZN,INDUS,CHAS,NX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
CREATE TABLE booston_house_price(
CRIM NUMBER(10,5) NOT NULL,
ZN NUMBER(5, 1) NOT NULL,
INDUS NUMBER(5, 2) NOT NULL,
CHAS NUMBER(1, 0) NOT NULL,
NX NUMBER(5,4) NOT NULL,
RM NUMBER(5, 3) NOT NULL,
AGE NUMBER(5, 1) NOT NULL,
DIS NUMBER(7, 4) NOT NULL,
RAD NUMBER(3, 0) NOT NULL,
TAX NUMBER(6, 1) NOT NULL,
PTRATIO NUMBER(4, 1) NOT NULL,
B NUMBER(6, 2) NOT NULL,
LSTAT NUMBER(5, 2) NOT NULL,
MEDV NUMBER(5, 1) NOT NULL 
);

DELETE FROM BOOSTON_HOUSE_PRICE;
COMMIT; 